using Newtonsoft.Json;
using PeterHan.PLib.Options;

namespace BiggerCapacity;

public partial class BiggerCapacity
{
	// PLib's shared root is mods/config/<assembly-name>. Resolve from there to
		// our own mods/settings/BiggerCapacityFixed/config.json in every installation.
		[ConfigFile("../../settings/BiggerCapacityFixed/config.json", true, true)]
	[RestartRequired]
	[JsonObject(MemberSerialization.OptIn)]
	public class Config
	{
		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.WIREMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.WIREMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.POWER")]
		[Limit(0.001, 1000)]
		public float WireMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.BATTERYMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.BATTERYMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.POWER")]
		[Limit(0.001, 1000)]
		public float BatteryMultiplier { get; set; } = 2f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GENERATORMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GENERATORMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.POWER")]
		[Limit(0.001, 1000)]
		public float GeneratorMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.TRANSFORMERMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.TRANSFORMERMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.POWER")]
		[Limit(0.001, 1000)]
		public float TransformerMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.STORAGEMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.STORAGEMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.STORAGE")]
		[Limit(0.001, 1000)]
		public float StorageMultiplier { get; set; } = 4f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.PIPEMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.PIPEMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.STORAGE")]
		[Limit(0.001, 1000)]
		public float PipeMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASPUMPMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASPUMPMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.STORAGE")]
		[Limit(0.001, 1000)]
		public float GasPumpMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDPUMPMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDPUMPMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.STORAGE")]
		[Limit(0.001, 1000)]
		public float LiquidPumpMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYORMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYORMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.STORAGE")]
		[Limit(0.001, 1000)]
		public float ConveyorMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.ROCKETFUELMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.ROCKETFUELMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.OTHER")]
		[Limit(0.001, 1000)]
		public float RocketFuelMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.ROCKETCARGOMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.ROCKETCARGOMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.OTHER")]
		[Limit(0.001, 1000)]
		public float RocketCargoMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.OTHERMULTIPLIER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.OTHERMULTIPLIER.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.OTHER")]
		[Limit(0.001, 1000)]
		public float OtherMultiplier { get; set; } = 1f;

		[JsonProperty]
		[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CAPACITY.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CAPACITY.TOOLTIP", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CATEGORIES.CAPACITY")]
		public Capacities Capacity { get; set; } = new Capacities();

		// Serialized for migration, but deliberately not exposed as a UI option.
		[JsonProperty]
		public int version { get; set; } = CONFIG_VERSION;

		[JsonObject(MemberSerialization.OptIn)]
		public class Capacities
		{
			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LOCKER.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LOCKER.TOOLTIP")]
			[Limit(1, 99999)]
			public int Locker { get; set; } = 20000;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.WOODSTORAGE.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.WOODSTORAGE.TOOLTIP")]
			[Limit(1, 99999)]
			public int WoodStorage { get; set; } = 20000;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDRESERVOIR.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDRESERVOIR.TOOLTIP")]
			[Limit(1, 99999)]
			public int LiquidReservoir { get; set; } = 5000;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASRESERVOIR.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASRESERVOIR.TOOLTIP")]
			[Limit(1, 99999)]
			public int GasReservoir { get; set; } = 150;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.RATIONBOX.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.RATIONBOX.TOOLTIP")]
			[Limit(1, 99999)]
			public int RationBox { get; set; } = 150;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.REFRIGERATOR.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.REFRIGERATOR.TOOLTIP")]
			[Limit(1, 99999)]
			public int Refrigerator { get; set; } = 100;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.MINIFRIDGE.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.MINIFRIDGE.TOOLTIP")]
			[Limit(1, 99999)]
			public int MiniFridge { get; set; } = 50;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.STORAGETILE.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.STORAGETILE.TOOLTIP")]
			[Limit(1, 99999)]
			public int StorageTile { get; set; } = 1000;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONDUCTIONPANEL.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONDUCTIONPANEL.TOOLTIP")]
			[Limit(0.001, 99999)]
			public float ConductionPanel { get; set; } = 10f;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASPUMP.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASPUMP.TOOLTIP")]
			[Limit(0.001, 99999)]
			public float GasPump { get; set; } = 0.5f;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASMINIPUMP.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASMINIPUMP.TOOLTIP")]
			[Limit(0.001, 99999)]
			public float GasMiniPump { get; set; } = 0.05f;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDPUMP.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDPUMP.TOOLTIP")]
			[Limit(0.001, 99999)]
			public float LiquidPump { get; set; } = 10f;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDMINIPUMP.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDMINIPUMP.TOOLTIP")]
			[Limit(0.001, 99999)]
			public float LiquidMiniPump { get; set; } = 1f;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CARGOBAY.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CARGOBAY.TOOLTIP")]
			[Limit(1, 99999)]
			public int CargoBay { get; set; } = 1000;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYORINBOX.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYORINBOX.TOOLTIP")]
			[Limit(1, 99999)]
			public int ConveyorInbox { get; set; } = 1000;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYOROUTBOX.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYOROUTBOX.TOOLTIP")]
			[Limit(1, 99999)]
			public int ConveyorOutbox { get; set; } = 1000;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYORRAILS.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.CONVEYORRAILS.TOOLTIP")]
			[Limit(1, 99999)]
			public int ConveyorRails { get; set; } = 20;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDPIPE.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.LIQUIDPIPE.TOOLTIP")]
			[Limit(0.001, 99999)]
			public float LiquidPipe { get; set; } = 10f;

			[JsonProperty]
			[Option("STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASPIPE.NAME", "STRINGS.BIGGERCAPACITYFIXED.OPTIONS.GASPIPE.TOOLTIP")]
			[Limit(0.001, 99999)]
			public float GasPipe { get; set; } = 1f;
		}
	}
}
